### ISSUE TITLE
Sound does not work on Ubuntu 22.04

### ISSUE THREAD

**Issue by GlazedBelmont** [devendor/c302ca#7]
Did the sound procedures and sound is not working

**Comment by syhan** [comment]
Me neither. :(

**Comment by GlazedBelmont** [comment]
yes, sadly this will need to be fixed one day, I am currently trying to get [Breath](https://github.com/cb-linux/breath/) working with sound along with the creator

if you want to use chromeOS with the uefi firmware, I recommend [Brunch](https://github.com/sebanc/brunch) and use this repo for the [brunch files](https://github.com/sebanc/brunch-unstable/releases)

**Comment by WeirdTreeThing** [comment]
@GlaZedBelmont sound works on my cave

**Comment by GlazedBelmont** [comment]
I will end you
